### ISSUE TITLE
Getting Error 403: Permission iam.serviceAccounts.signBlob is required when I have Service Account Token Creator role

### ISSUE THREAD

**Issue by mingzew** [GoogleCloudPlatform/professional-services#725]
Hi I am following through the guide for direct-upload-to-gcs, and I am keep getting the following msg when I try to generated a signed link

```sign: failed to sign, err = googleapi: Error 403: Permission iam.serviceAccounts.signBlob is required to perform this operation on service account projects/myapp-1234a/serviceAccounts/firebase-adminsdk-abcdef@myapp-1234a.iam.gserviceaccount.com., forbidden``` 

in the logs when my user. Yet in my `IAM & Admin` -> `IAM` I have the role of `Service Account Token Creator` and `Storage Admin` for my principal `firebase-adminsdk-abcdef@myapp-1234a.iam.gserviceaccount.com`.

My app.yaml looks like
```
runtime: go111
env_variables:
  UPLOADABLE_BUCKET: "hype-uploads"
  SERVICE_ACCOUNT: "firebase-adminsdk-abcdef@myapp-1234a.iam.gserviceaccount.com"
```

I have also modified `const signerUrl = "https://myapp-1234a.engine.url.appspot.com/sign"`

Am I missing something?
